# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desing.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 658)
        MainWindow.setMinimumSize(QtCore.QSize(658, 658))
        MainWindow.setMaximumSize(QtCore.QSize(658, 658))
        MainWindow.setBaseSize(QtCore.QSize(658, 658))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img-cha.jpg"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.Label_drawn_number = QtWidgets.QLabel(self.centralwidget)
        self.Label_drawn_number.setGeometry(QtCore.QRect(250, 430, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.Label_drawn_number.setFont(font)
        self.Label_drawn_number.setStyleSheet("color: rgb(0, 0, 0);")
        self.Label_drawn_number.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_drawn_number.setObjectName("Label_drawn_number")
        self.button_drawn_number = QtWidgets.QPushButton(self.centralwidget)
        self.button_drawn_number.setGeometry(QtCore.QRect(270, 550, 90, 28))
        self.button_drawn_number.setStyleSheet("\n"
"QPushButton {\n"
"     background-color: #3cbaa2; border: 1px solid black;\n"
"     border-radius: 5px;\n"
"}")
        self.button_drawn_number.setObjectName("button_drawn_number")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 360, 281, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"font: 75 18pt \"DejaVu Sans\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chá Rifa do Samuel"))
        self.Label_drawn_number.setText(_translate("MainWindow", "0"))
        self.button_drawn_number.setText(_translate("MainWindow", "Sortear"))
        self.label_2.setText(_translate("MainWindow", "Número sorteado foi:"))
import resources
